name: Publish Asherah-Cobhan

on:
  release:
    types: [published] # Trigger when release is created

jobs:
  build-linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: golang:bullseye
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
    - uses: actions/checkout@v2
    - name: Configure packages
      run: scripts/ubuntu-configure.sh
    - name: Build for Linux x64
      run: scripts/ubuntu-build-x64.sh
    - name: Build for Linux arm64
      run: scripts/ubuntu-build-arm64.sh
    - name: Upload Artifacts
      run: scripts/upload-artifacts.sh output/libasherah-x64.h output/libasherah-x64.so output/libasherah-arm64.h output/libasherah-arm64.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-macos:
    timeout-minutes: 15
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build for MacOS
      run: scripts/macos-build.sh
    - name: Upload Artifacts
      run: scripts/upload-artifacts.sh output/libasherah-darwin-x64.h output/libasherah-x64.dylib output/libasherah-darwin-arm64.h output/libasherah-arm64.dylib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
